# Generated by Django 4.2.13 on 2024-05-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryoption',
            options={'ordering': ['name'], 'verbose_name_plural': 'Delivery options'},
        ),
        migrations.AlterModelOptions(
            name='paymentoption',
            options={'ordering': ['name'], 'verbose_name_plural': 'Payment options'},
        ),
    ]
