# Generated by Django 4.2.13 on 2024-05-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_deliveryoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery options',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_option',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.DeleteModel(
            name='PaymentOption',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.deliveryprovider'),
        ),
        migrations.DeleteModel(
            name='DeliveryOption',
        ),
    ]
